### ISSUE TITLE
Fitting clothes on 3D models

### ISSUE THREAD

**Issue by usmannamjad** [liren2515/DIG#1]
Is there any way we can represent an obj/ply/fbx file in SMPL form?

**Comment by liren2515** [comment]
Sorry, I don't think I follow your question. What do you mean by "SMPL form'?

**Comment by usmannamjad** [comment]
Is there a way to get the SMPL pose and shape parameters from an obj/ply file.

**Comment by liren2515** [comment]
I think you can recover the SMPL parameters by minimizing the chamfer distance between the SMPL model and the give obj mesh w.r.t them.
