### ISSUE TITLE
How to compute the inflating SDF?

### ISSUE THREAD

**Issue by sunshineatnoon** [liren2515/DIG#6]
Hi, Thanks for open-sourcing this awesome project. In Sec.3.1 in the paper, the SDF is computed as UDF subtracting a small value, I couldn't find code of this process in the repo. Could you please point me to the code? Thanks!

**Comment by liren2515** [comment]
Hello, thanks for your interest in our work. We didn't include the processing codes in this repo. But computing SDF from UDF is quite straightforward as below:
```
mesh = trimesh.load('mesh.obj')
rand_pts = (np.random.rand(RAND_N,3) - 0.5) * 2
_, udf_rand_pts, _ = mesh.nearest.on_surface(rand_pts)
sdf_rand_pts = udf_rand_pts - thickness
```

`thickness` is the value to control the thickness of the surface. In our experiment, we set it to 0.01.

**Comment by sunshineatnoon** [comment]
Thanks so much!
